version: '3.4'

services:
  mootaeworld:
    image: luckyweb_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_URL: "postgresql+psycopg2://postgres:FC%qU[Scjz8#OE&R@172.17.0.1:5432/mootae_world"
      API_DOC: "true"
      NODE_ENV: production
      
    ports:
      - 2000:2000
    restart: always
    volumes:
      - ./public:/usr/src/app/public
