version: '3.4'

services:
  mootaeworld:
    image: luckyweb_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_URL: "postgresql+psycopg2://postgres:FC%25qU%5BScjz8%23OE%26R@203.154.68.141:5432/mootae_world"
      API_DOC: "true"
      NODE_ENV: production
    env_file:
      - ./home/DEEPNDEV/Mootae_World_Backend/environment/.env
    ports:
      - 2000:2000
    restart: always
    volumes:
      - ./public:/usr/src/app/public
