version: '3.4'

services:
  mootaeworld:
    image: luckyweb_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_URL: "postgresql://user:password@db:5432/mydb"
      API_DOC: "true"
      NODE_ENV: production
      
    ports:
      - 2000:2000
    restart: always
    volumes:
      - ./public:/usr/src/app/public
