version: '3.4'

services:
  mootaeworld:
    image: luckyweb_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_URL: "postgresql+psycopg2://postgres:FC%qU[Scjz8#OE&R@203.154.68.141:5432/mootae_world"
      API_DOC: "true"
      NODE_ENV: production
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      SECRET_KEY: "YOUR_SECRET_KEY_1234567890"
      REFRESH_SECRET_KEY: 7
      
    ports:
      - 2000:2000
    restart: always
    volumes:
      - ./public:/usr/src/app/public
